# Generated by Django 5.0 on 2024-10-07 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('HRid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('HRname', models.CharField(max_length=50)),
                ('HRpassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parttime',
            fields=[
                ('PTid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('PTname', models.CharField(max_length=50)),
                ('PTpassword', models.CharField(max_length=50)),
                ('PTphonenumber', models.CharField(max_length=50, null=True)),
                ('PTbankacc', models.CharField(max_length=50, null=True)),
                ('PTic', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payrollreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.parttime')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.parttime')),
            ],
        ),
    ]
