# Generated by Django 5.0 on 2024-10-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='PTid',
        ),
        migrations.DeleteModel(
            name='Payrollreport',
        ),
        migrations.DeleteModel(
            name='Payslip',
        ),
    ]
