# Generated by Django 5.0 on 2024-10-08 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_payslip_ptid_delete_payrollreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('PAYSLIPid', models.AutoField(primary_key=True, serialize=False)),
                ('PAYSLIPpayperiodstart', models.CharField(max_length=50)),
                ('PAYSLIPpayperiodend', models.CharField(max_length=50)),
                ('PAYSLIPtotalworkhour', models.CharField(max_length=5)),
                ('PAYSLIPtotalbreakhour', models.CharField(max_length=5)),
                ('PAYSLIPtotalsalary', models.CharField(max_length=50)),
                ('PTid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.parttime')),
            ],
        ),
    ]
