# Generated by Django 5.0 on 2024-10-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_payslip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttime',
            name='PTpassword',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
