# Generated by Django 5.0 on 2024-10-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_parttime_ptpassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payslip',
        ),
    ]
