# Generated by Django 5.0 on 2024-10-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_payslip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payslip',
        ),
    ]
